### ISSUE TITLE
Waiting on AWS EKS Features for completeness

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#44]
Wanted to compile an issue that follow the progress of several features we need from eks:
  - [ ] spot instances for managed node groups https://github.com/aws/containers-roadmap/issues/583
  - [X] private subnets for node groups https://github.com/aws/containers-roadmap/issues/607
  - [ ] support for autoscaling to zero https://github.com/aws/containers-roadmap/issues/724

**Comment by tylerpotts** [comment]
Don't need an issue to track this

**Comment by rsignell-usgs** [comment]
Is there a way to enable spot for the Dask worker pool?
