### ISSUE TITLE
Authentication via Keycloak

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#780]
## Summary

Currently jupyterhub is leaned on for all authentication and while it provides good authentication it does not enable many features that we need out of an authentication provider. 

## Proposed implementation

The difficulty of adding keycloak at this moment it integrating it with all of the existing infrastructure in QHub. This may also change a lot of the documentation.

 - [x] add keycloak helm chart to qhub. The helm chart will deploy keycloak along with a postgresql database
 - [x] add qhub config options for configuring email smtp credentials so that keycloak can email password resets etc. note this section should be a general section not tied to keycloak since other providers may want to sent email e.g. grafana and prometheus 
 - [x] auto-create a qhub realm and import users/groups (plus uid/gid)
 - [x] configure traefik-forward-auth to rely on keycloak to authenticate users
 - [x] configure jupyterhub to rely on keycloak for authentication 
 - [x] specify an initial root password for master realm in qhub-config.yaml
 - [x] allow github/Auth0 login to be auto-created where specified in qhub-config.yaml
 - [x] JH to properly get and understand groups for the user.
 - [x] Admin users from keycloak (members of admin group are admins in JupyterHub)
 - [x] JH to assign uid/gid from Keycloak, and generate new uid/gid where not present - maybe consider the work done in uidgidserver branch.
 - [x] JH logout to also logout of keycloak (some attempt is already there - search logout_redirect_url)
 - [x] Default setup should set users group as a default group for new users
 - [x] Replace "Sign in with OAuth 2.0" on /hub/login page and/or automatically redirect to QHub login page anyway
 - [ ] Hide password login form by default in Keycloak for Auth0/GitHub. Auto-forward to the IdP?
 - [x] Force existence of users and admin groups.
 - [x] No example-user should be created (just Keycloak root)
 - [x] Automated Cypress tests adjusted to work with Keycloak

Consider #835 
And then maybe need:
 - [x] An upgrade process
 - [x] Error: Top level group already exist if we change order in yaml file etc.
 - [x] Sort users and groups from yaml file for consistency, always generate admin/users groups if not present in yaml
 - [x] Don't break if the user is a member of 0 groups at all
 - [ ] initial root password should be generated on deploy or given in an env var
 - [x] Concept of primary_group may be lost in Keycloak, but still expected in the NFS (no longer relevant?)

## Acceptance Criteria

 - [ ] keycloak is deployed and running on cluster
 - [ ] keycloak ui is accessible via prefix path `https://<qhub-domain>/auth/*`
 - [ ] admin should be able to visit keycloak UI and configure using github authentication, email authentication, password authentication etc.
 - [ ] user's within the qhub-config.yaml are automatically created on keycloak realm. Admin should still be able to visit keycloak and delete/add users
 - [ ] jupyterhub login should behave normally and rely on keycloak for authentication.
 - [ ] single signon should rely on keycloak for authenticating users

**Comment by tylerpotts** [comment]
Per @danlester

**Comment by tylerpotts** [comment]
per: @danlester 
**startupScripts in the Helm installation**

This doesn't seem to be the right approach because the Keycloak server is not yet running.

E.g. to update the master realm's name:
```
startupScripts:
 ...
 qhubrealm.sh: |
   /opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin --password password
   /opt/jboss/keycloak/bin/kcadm.sh update realms/master -s displayName=KeycloakUpdated
```

The script would work once the server is running, but not before. Maybe it is possible to run the server temporarily.

However, it is possible to add a user like so:
```
  qhubadminuser.sh: |
    /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u admin -p password
```
but this one-off script seems to be using [deep internals of Keycloak](https://github.com/keycloak/keycloak/blob/master/distribution/feature-packs/server-feature-pack/src/main/resources/content/bin/add-user-keycloak.sh), and I don't think it is a sensible approach to do something similar for everything we may need.

**Comment by tylerpotts** [comment]
per: @danlester 
**Keycloak Operator**

Not sure how stable [this is](https://github.com/keycloak/keycloak-operator).

To install, I have cloned the repo and run `make cluster/prepare` to set up the CRDs.

Then `kubectl apply -f deploy/operator.yaml` on something similar to this [deploy/operator.yaml](https://github.com/keycloak/keycloak-operator/blob/master/deploy/operator.yaml).

Attempting to create a new realm using something like [this YAML](https://www.keycloak.org/docs/latest/server_installation/index.html#_realm-cr).

It doesn't work yet. Might be due to different namespace, or maybe we need to install Keycloak through the operator too (currently installed via Helm).

**Comment by tylerpotts** [comment]
per: @danlester 
**Keycloak Terraform Provider**

I have been able to use [Terraform Keycloak Provider](https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs) to successfully create a realm. (See keycloak-provider branch.) However, we will also need to separate the terraform apply into separate sections. Keycloak will need to be running before the terraform provider can access it.

One challenge will be to understand when Keycloak config needs updating and when it should be ignored. For example, if the admin password is changed manually within Keycloak, a `qhub deploy` should probably not overwrite it again with something else.

We would have to create a `qhub-bot` user with a secret password in the `master` realm to use in the Terraform keycloak provider. For other Keycloak API access, e.g. if needed from JupyterHub, we may be able to configure separate clients.

**Changes in qhub-config.yaml and qhub init**

qhub-config.yaml will now need an extra 'keycloak-admin-password' field, separate from the users section.
`qhub init`will still generate one password which it will attach to both the keycloak-admin-password and example-user.password fields in its initial qhub-config.yaml.

QHub will create a user called `admin` with the supplied password in the `master` realm. It will also create a `qhub` realm containing example-user and any other users specified.

qhub-config.yaml will need the authentication section to be changed so that each possible auth type (Auth0, GitHub, password) can potentially be used simultaneously. An upgrade script would translate what we have now (just one provider) to that one provider being the only one configured - but more could be added. `qhub init` could probably remain the same in this regard - only accept one auth type, even though it is technically possible to specify multiple in the qhub-config.yaml.

In the users section, uid/gid should be optional - but imported if specified. Users that were created manually in Keycloak but are not specified in qhub-config.yaml should not be deleted.

(Precise field names and yaml layout above are not final...)

**Changes to Jupyterhub_config.py**

We will need some way to set unique uid/gid values within JupyterHub. And retrieve them in bulk. Maybe a separate service to create and cache these will be needed.

**Comment by danlester** [comment]
Can Traefik ForwardAuth allow us to restrict a qhubextension to admin group members only?
It would need a separate instance of the forwardauth deployment using a different Keycloak client.
It [looks like Keycloak](https://www.keycloak.org/docs/latest/authorization_services/#_getting_started_hello_world_enabling_authz_services) can set up permissions like that.
But I don't believe that [Traefik ForwardAuth](https://github.com/thomseddon/traefik-forward-auth) checks the resource permission anyway.

**Comment by danlester** [comment]
In the work in progress, you set `initial_root_password` in the yaml file so that there is a password for root Keycloak user. This is plain text, and only works the first time keycloak is deployed - if you change it in the yaml and redeploy, it won't update in keycloak.

It would be better if we could generate a random password on first *deploy* (not at *init*) and display if so. For automation purposes, if an env var is set it would take the password from there instead of generating it.

However, I don't think there is a way to find out if the helm deployment happened for the first time. If we could find that out, we could notify the user that the password has been set and let them know what it is. If there is no way to find this out, we instead have to say "here is what the password will be if this was the first time deploying keycloak, but it might actually be something from a previous deployment".

A workaround could be to attempt an automated behind-the-scenes login with the 'potentially-new' password and only notify the user if that worked.

So the question is - any way to find out whether a helm deployment happened for the first time and (I guess) output it to the screen like we do with the IP address?

**Comment by danlester** [comment]
Closing. Keycloak is in main now. There are a couple of ideas in the task list above that we might still want to explore one day, but think we should deal with that whenever we do.
