### ISSUE TITLE
Release v0.3.14

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#934]
The work for this release lives in the `v0.3.14` branch. There remains a bug detailed in #933 that is preventing smooth deployment and should be fixed before this release is cut.

This release is meant to be a hotfix and includes the following commits pulled from main:
- [x] Fixed bug due to an unpinned GCP terraform dependency preventing deployment on GCP ([#914](https://github.com/Quansight/qhub/pull/914))
- [x] Deletes existing `.gitlb-ciy.yml` when rendering ([#887](https://github.com/Quansight/qhub/pull/887))
- [x] Update default CDS dashboards version to 0.6.0 ([this commit](https://github.com/Quansight/qhub/commit/188a5612d169bac0c43f640417031b257b71289b))
- [x] Update Azure env variable names in terraform ([#882](https://github.com/Quansight/qhub/pull/882))

**Comment by trallard** [comment]
Can this be closed since 0.4 is underway?

**Comment by iameskild** [comment]
I believe so. Closing.
